/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaForm;

/**
 *
 * @author acer
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    int XX, YY;
    boolean qlhd, qlk = false,qlnv = false, qlncc = false, tk = false, ttkh = false;
    public AdminForm(String name) {
        this.qlhd = true;
        initComponents();
        jLabel2.setText(name);
        jPanelQLDH.setBackground(new java.awt.Color(15,116,182));
        jPanelBody.removeAll();
        jPanelBody.repaint();
        jPanelBody.revalidate();
        jPanelBody.add(jDashboardQLDH);
        jPanelBody.repaint();
        jPanelBody.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBackground = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelTK = new javax.swing.JPanel();
        jLabelTK = new javax.swing.JLabel();
        jPanelQLNV = new javax.swing.JPanel();
        jLabelQLNV = new javax.swing.JLabel();
        jPanelQLNCC = new javax.swing.JPanel();
        jLabelQLNCC = new javax.swing.JLabel();
        jPanelQLK = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelQLDH = new javax.swing.JPanel();
        jLabelQLDH = new javax.swing.JLabel();
        jPanelTTKH = new javax.swing.JPanel();
        jLabelTTKH = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jDashboardQLDH = new javax.swing.JPanel();
        jDashboardQLK = new javax.swing.JPanel();
        jDashboardQLNCC = new javax.swing.JPanel();
        jDashboardQLNV = new javax.swing.JPanel();
        jDashboardTK = new javax.swing.JPanel();
        jDashboardTTKH = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);

        jBackground.setBackground(new java.awt.Color(255, 255, 255));
        jBackground.setForeground(new java.awt.Color(255, 255, 255));
        jBackground.setPreferredSize(new java.awt.Dimension(1600, 900));
        jBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jBackgroundMouseDragged(evt);
            }
        });
        jBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBackgroundMousePressed(evt);
            }
        });
        jBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_2.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        jBackground.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1567, 0, 30, 30));

        btnMinimize.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_minimize_window_25px.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        jBackground.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1545, 0, 20, 30));

        jPanelMenu.setBackground(new java.awt.Color(0, 0, 0));
        jPanelMenu.setForeground(new java.awt.Color(0, 0, 0));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_gear_100px_1.png"))); // NOI18N
        jLabel6.setText("KMA-Gear");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 150));

        jPanelTK.setBackground(new java.awt.Color(0, 0, 0));
        jPanelTK.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTKMouseExited(evt);
            }
        });

        jLabelTK.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTK.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_area_chart_30px.png"))); // NOI18N
        jLabelTK.setText("Thống kê");
        jLabelTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelTKLayout = new javax.swing.GroupLayout(jPanelTK);
        jPanelTK.setLayout(jPanelTKLayout);
        jPanelTKLayout.setHorizontalGroup(
            jPanelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTKLayout.createSequentialGroup()
                .addComponent(jLabelTK, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 125, Short.MAX_VALUE))
        );
        jPanelTKLayout.setVerticalGroup(
            jPanelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTKLayout.createSequentialGroup()
                .addComponent(jLabelTK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanelTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 270, 60));

        jPanelQLNV.setBackground(new java.awt.Color(0, 0, 0));
        jPanelQLNV.setForeground(new java.awt.Color(0, 0, 0));
        jPanelQLNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelQLNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelQLNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelQLNVMouseExited(evt);
            }
        });

        jLabelQLNV.setBackground(new java.awt.Color(255, 255, 255));
        jLabelQLNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQLNV.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQLNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_staff_30px.png"))); // NOI18N
        jLabelQLNV.setText("Quản lý nhân viên");

        javax.swing.GroupLayout jPanelQLNVLayout = new javax.swing.GroupLayout(jPanelQLNV);
        jPanelQLNV.setLayout(jPanelQLNVLayout);
        jPanelQLNVLayout.setHorizontalGroup(
            jPanelQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLNVLayout.createSequentialGroup()
                .addComponent(jLabelQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        jPanelQLNVLayout.setVerticalGroup(
            jPanelQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelMenu.add(jPanelQLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 270, 60));

        jPanelQLNCC.setBackground(new java.awt.Color(0, 0, 0));
        jPanelQLNCC.setForeground(new java.awt.Color(0, 0, 0));
        jPanelQLNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelQLNCCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelQLNCCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelQLNCCMouseExited(evt);
            }
        });

        jLabelQLNCC.setBackground(new java.awt.Color(255, 255, 255));
        jLabelQLNCC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQLNCC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQLNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_supplier_30px.png"))); // NOI18N
        jLabelQLNCC.setText("Quản lý nhà cung cấp");

        javax.swing.GroupLayout jPanelQLNCCLayout = new javax.swing.GroupLayout(jPanelQLNCC);
        jPanelQLNCC.setLayout(jPanelQLNCCLayout);
        jPanelQLNCCLayout.setHorizontalGroup(
            jPanelQLNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLNCCLayout.createSequentialGroup()
                .addComponent(jLabelQLNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanelQLNCCLayout.setVerticalGroup(
            jPanelQLNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelQLNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelMenu.add(jPanelQLNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 270, 60));

        jPanelQLK.setBackground(new java.awt.Color(0, 0, 0));
        jPanelQLK.setForeground(new java.awt.Color(0, 0, 0));
        jPanelQLK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelQLKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelQLKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelQLKMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_warehouse_30px.png"))); // NOI18N
        jLabel1.setText("Quản lý kho hàng");

        javax.swing.GroupLayout jPanelQLKLayout = new javax.swing.GroupLayout(jPanelQLK);
        jPanelQLK.setLayout(jPanelQLKLayout);
        jPanelQLKLayout.setHorizontalGroup(
            jPanelQLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLKLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        jPanelQLKLayout.setVerticalGroup(
            jPanelQLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelMenu.add(jPanelQLK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 60));

        jPanelQLDH.setBackground(new java.awt.Color(0, 0, 0));
        jPanelQLDH.setForeground(new java.awt.Color(0, 0, 0));
        jPanelQLDH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelQLDHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelQLDHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelQLDHMouseExited(evt);
            }
        });

        jLabelQLDH.setBackground(new java.awt.Color(255, 255, 255));
        jLabelQLDH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQLDH.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQLDH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_bill_30px.png"))); // NOI18N
        jLabelQLDH.setText("Quản lý đơn hàng");

        javax.swing.GroupLayout jPanelQLDHLayout = new javax.swing.GroupLayout(jPanelQLDH);
        jPanelQLDH.setLayout(jPanelQLDHLayout);
        jPanelQLDHLayout.setHorizontalGroup(
            jPanelQLDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLDHLayout.createSequentialGroup()
                .addComponent(jLabelQLDH, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );
        jPanelQLDHLayout.setVerticalGroup(
            jPanelQLDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLDHLayout.createSequentialGroup()
                .addComponent(jLabelQLDH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanelQLDH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 270, 60));

        jPanelTTKH.setBackground(new java.awt.Color(0, 0, 0));
        jPanelTTKH.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTTKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelTTKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTTKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTTKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTTKHMouseExited(evt);
            }
        });

        jLabelTTKH.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTTKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTTKH.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTTKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTTKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_customer_insight_30px.png"))); // NOI18N
        jLabelTTKH.setText("Thông tin khách hàng");
        jLabelTTKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelTTKHLayout = new javax.swing.GroupLayout(jPanelTTKH);
        jPanelTTKH.setLayout(jPanelTTKHLayout);
        jPanelTTKHLayout.setHorizontalGroup(
            jPanelTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTTKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelTTKHLayout.setVerticalGroup(
            jPanelTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTTKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelMenu.add(jPanelTTKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 270, 60));

        jBackground.add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 900));

        jPanelBody.setLayout(new java.awt.CardLayout());

        jDashboardQLDH.setBackground(new java.awt.Color(153, 255, 153));
        jDashboardQLDH.setForeground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jDashboardQLDHLayout = new javax.swing.GroupLayout(jDashboardQLDH);
        jDashboardQLDH.setLayout(jDashboardQLDHLayout);
        jDashboardQLDHLayout.setHorizontalGroup(
            jDashboardQLDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jDashboardQLDHLayout.setVerticalGroup(
            jDashboardQLDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanelBody.add(jDashboardQLDH, "card4");

        jDashboardQLK.setBackground(new java.awt.Color(153, 153, 255));
        jDashboardQLK.setForeground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jDashboardQLKLayout = new javax.swing.GroupLayout(jDashboardQLK);
        jDashboardQLK.setLayout(jDashboardQLKLayout);
        jDashboardQLKLayout.setHorizontalGroup(
            jDashboardQLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jDashboardQLKLayout.setVerticalGroup(
            jDashboardQLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanelBody.add(jDashboardQLK, "card3");

        jDashboardQLNCC.setBackground(new java.awt.Color(255, 153, 153));
        jDashboardQLNCC.setForeground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jDashboardQLNCCLayout = new javax.swing.GroupLayout(jDashboardQLNCC);
        jDashboardQLNCC.setLayout(jDashboardQLNCCLayout);
        jDashboardQLNCCLayout.setHorizontalGroup(
            jDashboardQLNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jDashboardQLNCCLayout.setVerticalGroup(
            jDashboardQLNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanelBody.add(jDashboardQLNCC, "card5");

        jDashboardQLNV.setBackground(new java.awt.Color(255, 255, 204));
        jDashboardQLNV.setForeground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jDashboardQLNVLayout = new javax.swing.GroupLayout(jDashboardQLNV);
        jDashboardQLNV.setLayout(jDashboardQLNVLayout);
        jDashboardQLNVLayout.setHorizontalGroup(
            jDashboardQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jDashboardQLNVLayout.setVerticalGroup(
            jDashboardQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanelBody.add(jDashboardQLNV, "card5");

        jDashboardTK.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jDashboardTKLayout = new javax.swing.GroupLayout(jDashboardTK);
        jDashboardTK.setLayout(jDashboardTKLayout);
        jDashboardTKLayout.setHorizontalGroup(
            jDashboardTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jDashboardTKLayout.setVerticalGroup(
            jDashboardTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanelBody.add(jDashboardTK, "card5");

        jDashboardTTKH.setBackground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout jDashboardTTKHLayout = new javax.swing.GroupLayout(jDashboardTTKH);
        jDashboardTTKH.setLayout(jDashboardTTKHLayout);
        jDashboardTTKHLayout.setHorizontalGroup(
            jDashboardTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jDashboardTTKHLayout.setVerticalGroup(
            jDashboardTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanelBody.add(jDashboardTTKH, "card8");

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("jLabel4");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(555, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jScrollPane.setViewportView(jPanel1);

        jPanelBody.add(jScrollPane, "card2");

        jBackground.add(jPanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 1330, 670));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jBackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 120, 60));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "taideptrai", "anhtai3d2y", "true"},
                {"2", "taideptrai1", "anhtai3d2y", null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Username", "Password", "Isadmin"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 360, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1600, 900));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackgroundMousePressed
        // TODO add your handling code here:
        XX = evt.getX();
        YY = evt.getY();
    }//GEN-LAST:event_jBackgroundMousePressed

    private void jBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackgroundMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - XX, y - YY);
    }//GEN-LAST:event_jBackgroundMouseDragged

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_3.png")));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_2.png")));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AdminForm.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        // TODO add your handling code here:
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_minimize_window_25px_1.png")));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        // TODO add your handling code here:
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_minimize_window_25px.png")));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void jPanelQLDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLDHMouseClicked
        // TODO add your handling code here:
        qlhd = true;
        qlk = false;
        qlnv = false;
        qlncc = false;
        tk = false;
        ttkh = false;
        jPanelQLDH.setBackground(new java.awt.Color(15,116,182));
        jPanelQLK.setBackground(new java.awt.Color(0,0,0));
        jPanelQLNV.setBackground(new java.awt.Color(0,0,0));
        jPanelQLNCC.setBackground(new java.awt.Color(0,0,0));
        jPanelTK.setBackground(new java.awt.Color(0,0,0));
        jPanelTTKH.setBackground(new java.awt.Color(0,0,0));
        jPanelBody.removeAll();
        jPanelBody.repaint();
        jPanelBody.revalidate();
        jPanelBody.add(jDashboardQLDH);
        jPanelBody.repaint();
        jPanelBody.revalidate();
    }//GEN-LAST:event_jPanelQLDHMouseClicked

    private void jPanelQLKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLKMouseClicked
        // TODO add your handling code here:
        qlhd = false;
        qlk = true;
        qlnv = false;
        qlncc = false;
        tk = false;
        ttkh = false;
        jPanelQLDH.setBackground(new java.awt.Color(0,0,0));
        jPanelQLK.setBackground(new java.awt.Color(15,116,182));
        jPanelQLNV.setBackground(new java.awt.Color(0,0,0));
        jPanelQLNCC.setBackground(new java.awt.Color(0,0,0));
        jPanelTK.setBackground(new java.awt.Color(0,0,0));
        jPanelTTKH.setBackground(new java.awt.Color(0,0,0));
        jPanelBody.removeAll();
        jPanelBody.repaint();
        jPanelBody.revalidate();
        jPanelBody.add(jDashboardQLK);
        jPanelBody.repaint();
        jPanelBody.revalidate();
    }//GEN-LAST:event_jPanelQLKMouseClicked

    private void jPanelQLNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLNCCMouseClicked
        // TODO add your handling code here:
        qlhd = false;
        qlk = false;
        qlnv = false;
        qlncc = true;
        tk = false;
        ttkh = false;
        jPanelQLDH.setBackground(new java.awt.Color(0,0,0));
        jPanelQLK.setBackground(new java.awt.Color(0,0,0));
        jPanelQLNV.setBackground(new java.awt.Color(0,0,0));
        jPanelQLNCC.setBackground(new java.awt.Color(15,116,182));
        jPanelTK.setBackground(new java.awt.Color(0,0,0));
        jPanelTTKH.setBackground(new java.awt.Color(0,0,0));
        jPanelBody.removeAll();
        jPanelBody.repaint();
        jPanelBody.revalidate();
        jPanelBody.add(jDashboardQLNCC);
        jPanelBody.repaint();
        jPanelBody.revalidate();
    }//GEN-LAST:event_jPanelQLNCCMouseClicked

    private void jPanelQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLNVMouseClicked
        // TODO add your handling code here:
        qlhd = false;
        qlk = false;
        qlnv = true;
        qlncc = false;
        tk = false;
        ttkh = false;
        jPanelQLDH.setBackground(new java.awt.Color(0,0,0));
        jPanelQLK.setBackground(new java.awt.Color(0,0,0));
        jPanelQLNV.setBackground(new java.awt.Color(15,116,182));
        jPanelQLNCC.setBackground(new java.awt.Color(0,0,0));
        jPanelTK.setBackground(new java.awt.Color(0,0,0));
        jPanelTTKH.setBackground(new java.awt.Color(0,0,0));
        jPanelBody.removeAll();
        jPanelBody.repaint();
        jPanelBody.revalidate();
        jPanelBody.add(jDashboardQLNV);
        jPanelBody.repaint();
        jPanelBody.revalidate();
    }//GEN-LAST:event_jPanelQLNVMouseClicked

    private void jPanelTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTKMouseClicked
        // TODO add your handling code here:
        qlhd = false;
        qlk = false;
        qlnv = false;
        qlncc = false;
        tk = true;
        ttkh = false;
        jPanelQLDH.setBackground(new java.awt.Color(0,0,0));
        jPanelQLK.setBackground(new java.awt.Color(0,0,0));
        jPanelQLNV.setBackground(new java.awt.Color(0,0,0));
        jPanelQLNCC.setBackground(new java.awt.Color(0,0,0));
        jPanelTK.setBackground(new java.awt.Color(15,116,182));
        jPanelTTKH.setBackground(new java.awt.Color(0,0,0));
        jPanelBody.removeAll();
        jPanelBody.repaint();
        jPanelBody.revalidate();
        jPanelBody.add(jDashboardTK);
        jPanelBody.repaint();
        jPanelBody.revalidate();
    }//GEN-LAST:event_jPanelTKMouseClicked

    private void jPanelQLDHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLDHMouseEntered
        // TODO add your handling code here:
        if(!qlhd){
            jPanelQLDH.setBackground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_jPanelQLDHMouseEntered

    private void jPanelQLDHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLDHMouseExited
        // TODO add your handling code here:
        if(!qlhd){
            jPanelQLDH.setBackground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_jPanelQLDHMouseExited

    private void jPanelQLKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLKMouseEntered
        // TODO add your handling code here:
        if(!qlk){
            jPanelQLK.setBackground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_jPanelQLKMouseEntered

    private void jPanelQLKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLKMouseExited
        // TODO add your handling code here:
        if(!qlk){
            jPanelQLK.setBackground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_jPanelQLKMouseExited

    private void jPanelQLNCCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLNCCMouseEntered
        // TODO add your handling code here:
        if(!qlncc){
            jPanelQLNCC.setBackground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_jPanelQLNCCMouseEntered

    private void jPanelQLNCCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLNCCMouseExited
        // TODO add your handling code here:
        if(!qlncc){
            jPanelQLNCC.setBackground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_jPanelQLNCCMouseExited

    private void jPanelQLNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLNVMouseEntered
        // TODO add your handling code here:
        if(!qlnv){
            jPanelQLNV.setBackground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_jPanelQLNVMouseEntered

    private void jPanelQLNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLNVMouseExited
        // TODO add your handling code here:
        if(!qlnv){
            jPanelQLNV.setBackground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_jPanelQLNVMouseExited

    private void jPanelTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTKMouseEntered
        // TODO add your handling code here:
        if(!tk){
            jPanelTK.setBackground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_jPanelTKMouseEntered

    private void jPanelTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTKMouseExited
        // TODO add your handling code here:
        if(!tk){
            jPanelTK.setBackground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_jPanelTKMouseExited

    private void jPanelTTKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTTKHMouseClicked
        // TODO add your handling code here:
        qlhd = false;
        qlk = false;
        qlnv = false;
        qlncc = false;
        tk = false;
        ttkh = true;
        jPanelQLDH.setBackground(new java.awt.Color(0,0,0));
        jPanelQLK.setBackground(new java.awt.Color(0,0,0));
        jPanelQLNV.setBackground(new java.awt.Color(0,0,0));
        jPanelQLNCC.setBackground(new java.awt.Color(0,0,0));
        jPanelTK.setBackground(new java.awt.Color(0,0,0));
        jPanelTTKH.setBackground(new java.awt.Color(15,116,182));
        jPanelBody.removeAll();
        jPanelBody.repaint();
        jPanelBody.revalidate();
        jPanelBody.add(jDashboardTTKH);
        jPanelBody.repaint();
        jPanelBody.revalidate();
    }//GEN-LAST:event_jPanelTTKHMouseClicked

    private void jPanelTTKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTTKHMouseEntered
        // TODO add your handling code here:
        if(!ttkh){
            jPanelTTKH.setBackground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_jPanelTTKHMouseEntered

    private void jPanelTTKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTTKHMouseExited
        // TODO add your handling code here:
        if(!ttkh){
            jPanelTTKH.setBackground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_jPanelTTKHMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jLabel2.setText(new LoginForm().getUsername());
    }//GEN-LAST:event_jLabel2MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm("hi").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JPanel jBackground;
    private javax.swing.JPanel jDashboardQLDH;
    private javax.swing.JPanel jDashboardQLK;
    private javax.swing.JPanel jDashboardQLNCC;
    private javax.swing.JPanel jDashboardQLNV;
    private javax.swing.JPanel jDashboardTK;
    private javax.swing.JPanel jDashboardTTKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelQLDH;
    private javax.swing.JLabel jLabelQLNCC;
    private javax.swing.JLabel jLabelQLNV;
    private javax.swing.JLabel jLabelTK;
    private javax.swing.JLabel jLabelTTKH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelQLDH;
    private javax.swing.JPanel jPanelQLK;
    private javax.swing.JPanel jPanelQLNCC;
    private javax.swing.JPanel jPanelQLNV;
    private javax.swing.JPanel jPanelTK;
    private javax.swing.JPanel jPanelTTKH;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
