/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaForm;

import JavaClassObject.My_CNX;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    int XX, YY;
    public String un;
    public String getUsername(){
        return un;
    }

    public LoginForm() {
        initComponents();
//        jLabelMK.setVisible(true);
//        jLabelTK.setVisible(true);
        jErrorIcon1.setVisible(false);
        jErrorIcon2.setVisible(false);
        jClearPassword.setVisible(false);
        jClearUsername.setVisible(false);
    }
    public void Signin(){
        btnSign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePng/SignButtonGray.png")));
        lbWrongPass.setText("");
        lbQuenMK.setText("");
        lbWrongUsername.setText("");
        jErrorIcon1.setVisible(false);
        jErrorIcon2.setVisible(false);
        String userName = txtUsername.getText();
        String passWord = String.valueOf(jPasswordField.getPassword());
        String Sql = "select * from users where username = '" + userName + "'";
        if ("".equals(userName) || "".equals(passWord)) {
            lbWrongPass.setText("Bạn chưa điền đủ thông tin đăng nhập!");
        } else {
            try {
                Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost/qlbh", "root", "");
                Statement myStmt = myConn.createStatement();
                ResultSet myRs = myStmt.executeQuery(Sql);
                boolean checkPassword = false;
                boolean checkUsername = false;
                while (myRs.next()) {
                    checkUsername = userName.equals(myRs.getString("username"));
                    if (checkUsername) {
                        checkPassword = passWord.equals(myRs.getString("password"));
                        if (checkPassword) {
                            if (myRs.getBoolean("isadmin")) {
                                AdminForm af = new AdminForm(txtUsername.getText());
                                af.setVisible(true);
                                af.pack();
                                af.setLocationRelativeTo(null);
                                
                            } else {
                                StaffForm sf = new StaffForm();
                                sf.setVisible(true);
                                sf.pack();
//                                sf.setLocationRelativeTo(null);
                            }
                            this.dispose();
                        } else {
                            lbWrongPass.setText("Mật khẩu không chính xác.");
                            lbQuenMK.setText("Quên mật khẩu?");
                            jErrorIcon2.setVisible(true);
                        }
                        break;
                    }
//                System.out.println("Id: " + myRs.getString("id") + "\nUsername: " + myRs.getString("username") + "\nPassword: " + myRs.getString("password"));
                }
                if (!checkUsername) {
                    lbWrongUsername.setText("Tài khoản không tồn tại.");
                    jErrorIcon1.setVisible(true);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBackground = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jClearPassword = new javax.swing.JLabel();
        jClearUsername = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jLabelSign = new javax.swing.JLabel();
        btnSign = new javax.swing.JLabel();
        jErrorIcon2 = new javax.swing.JLabel();
        jErrorIcon1 = new javax.swing.JLabel();
        jSeparatorPass = new javax.swing.JSeparator();
        jSeparatorUsername = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLook = new javax.swing.JLabel();
        jUsericon = new javax.swing.JLabel();
        lbQuenMK = new javax.swing.JLabel();
        lbWrongUsername = new javax.swing.JLabel();
        lbWrongPass = new javax.swing.JLabel();
        lbDangNhap = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        lbDiscord = new javax.swing.JLabel();
        lbExit = new javax.swing.JLabel();
        lbRazer = new javax.swing.JLabel();
        lbTwitch = new javax.swing.JLabel();
        lbController = new javax.swing.JLabel();
        lbDell = new javax.swing.JLabel();
        lbGarena = new javax.swing.JLabel();
        lbCorsair = new javax.swing.JLabel();
        lbLogitech = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnBackground.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnBackgroundMouseDragged(evt);
            }
        });
        pnBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnBackgroundMousePressed(evt);
            }
        });
        pnBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        pnBackground.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        txtUsername.setBackground(new java.awt.Color(0, 0, 0));
        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setToolTipText("");
        txtUsername.setBorder(null);
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUsernameMouseExited(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });
        pnBackground.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 200, 40));

        jPasswordField.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField.setBorder(null);
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });
        jPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPasswordFieldMouseExited(evt);
            }
        });
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
        });
        pnBackground.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 200, 40));

        jClearPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jClearPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_cancel_15px.png"))); // NOI18N
        jClearPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jClearPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClearPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jClearPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jClearPasswordMouseExited(evt);
            }
        });
        pnBackground.add(jClearPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 50, 40));

        jClearUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jClearUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_cancel_15px.png"))); // NOI18N
        jClearUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jClearUsername.setRequestFocusEnabled(false);
        jClearUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClearUsernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jClearUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jClearUsernameMouseExited(evt);
            }
        });
        pnBackground.add(jClearUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 50, 40));

        btnMinimize.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(0, 0, 0));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_minimize_window_25px.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        pnBackground.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 20, 30));

        jLabelSign.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSign.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelSign.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSign.setText("Đăng nhập");
        jLabelSign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnBackground.add(jLabelSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 130, 40));

        btnSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePng/SignButtonGreen.png"))); // NOI18N
        btnSign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignMouseExited(evt);
            }
        });
        pnBackground.add(btnSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 200, 80));

        jErrorIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jErrorIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_error_20px.png"))); // NOI18N
        pnBackground.add(jErrorIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 20, 20));

        jErrorIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jErrorIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_error_20px.png"))); // NOI18N
        pnBackground.add(jErrorIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 20, 20));

        jSeparatorPass.setForeground(new java.awt.Color(255, 255, 255));
        pnBackground.add(jSeparatorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 280, 10));

        jSeparatorUsername.setForeground(new java.awt.Color(255, 255, 255));
        pnBackground.add(jSeparatorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 280, 10));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("K M A - G E A R");
        pnBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jLook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_lock_20px.png"))); // NOI18N
        pnBackground.add(jLook, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 30, 40));

        jUsericon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUsericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_user_20px.png"))); // NOI18N
        pnBackground.add(jUsericon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 30, 40));

        lbQuenMK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbQuenMK.setForeground(new java.awt.Color(255, 102, 102));
        lbQuenMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuenMK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbQuenMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbQuenMKMouseExited(evt);
            }
        });
        pnBackground.add(lbQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 120, 20));

        lbWrongUsername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbWrongUsername.setForeground(new java.awt.Color(255, 102, 102));
        lbWrongUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnBackground.add(lbWrongUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 320, 20));

        lbWrongPass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbWrongPass.setForeground(new java.awt.Color(255, 102, 102));
        lbWrongPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnBackground.add(lbWrongPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 320, 20));

        lbDangNhap.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        lbDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_gear_125px.png"))); // NOI18N
        pnBackground.add(lbDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 110, 110));

        lbLogin.setForeground(new java.awt.Color(255, 0, 0));
        lbLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaForm/Login.png"))); // NOI18N
        pnBackground.add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 390, 560));

        lbDiscord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_discord_100px.png"))); // NOI18N
        lbDiscord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDiscordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDiscordMouseExited(evt);
            }
        });
        pnBackground.add(lbDiscord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 300, 100, 70));

        lbExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbExit.setForeground(new java.awt.Color(0, 0, 0));
        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_2.png"))); // NOI18N
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbExitMouseExited(evt);
            }
        });
        pnBackground.add(lbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 30, 30));

        lbRazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_razer_100px.png"))); // NOI18N
        lbRazer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRazerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbRazerMouseExited(evt);
            }
        });
        pnBackground.add(lbRazer, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 100, 90));

        lbTwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_twitch_100px.png"))); // NOI18N
        lbTwitch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbTwitchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbTwitchMouseExited(evt);
            }
        });
        pnBackground.add(lbTwitch, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 100, 90));

        lbController.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_game_controller_100px_2.png"))); // NOI18N
        lbController.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbControllerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbControllerMouseExited(evt);
            }
        });
        pnBackground.add(lbController, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 100, 90));

        lbDell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_dell_100px_2.png"))); // NOI18N
        lbDell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDellMouseExited(evt);
            }
        });
        pnBackground.add(lbDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 100, 90));

        lbGarena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_garena_100px_2.png"))); // NOI18N
        lbGarena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbGarenaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbGarenaMouseExited(evt);
            }
        });
        pnBackground.add(lbGarena, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 120, 100, 90));

        lbCorsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_corsair_100px_2.png"))); // NOI18N
        lbCorsair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCorsairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCorsairMouseExited(evt);
            }
        });
        pnBackground.add(lbCorsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 100, 90));

        lbLogitech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_logitech_100px_2.png"))); // NOI18N
        lbLogitech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbLogitechMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbLogitechMouseExited(evt);
            }
        });
        pnBackground.add(lbLogitech, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 100, 90));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePng/371905140_ROBOT_WAVING_400px.gif"))); // NOI18N
        pnBackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1210, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbDiscordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDiscordMouseEntered
        // TODO add your handling code here:
        lbDiscord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_discord_100px_1.png")));
    }//GEN-LAST:event_lbDiscordMouseEntered

    private void lbDiscordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDiscordMouseExited
        // TODO add your handling code here:
        lbDiscord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_discord_100px.png")));
    }//GEN-LAST:event_lbDiscordMouseExited

    private void lbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseEntered
        // TODO add your handling code here:
        lbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_3.png")));
    }//GEN-LAST:event_lbExitMouseEntered

    private void lbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseExited
        // TODO add your handling code here:
        lbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_2.png")));
    }//GEN-LAST:event_lbExitMouseExited

    private void lbTwitchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTwitchMouseEntered
        // TODO add your handling code here:
        lbTwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_twitch_100px_1.png")));
    }//GEN-LAST:event_lbTwitchMouseEntered

    private void lbTwitchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTwitchMouseExited
        // TODO add your handling code here:
        lbTwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_twitch_100px.png")));
    }//GEN-LAST:event_lbTwitchMouseExited

    private void lbControllerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbControllerMouseEntered
        // TODO add your handling code here:
        lbController.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_game_controller_100px_1.png")));
    }//GEN-LAST:event_lbControllerMouseEntered

    private void lbControllerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbControllerMouseExited
        // TODO add your handling code here:
        lbController.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_game_controller_100px_2.png")));
    }//GEN-LAST:event_lbControllerMouseExited

    private void lbDellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDellMouseEntered
        // TODO add your handling code here:
        lbDell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_dell_100px_1.png")));
    }//GEN-LAST:event_lbDellMouseEntered

    private void lbDellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDellMouseExited
        // TODO add your handling code here:
        lbDell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_dell_100px_2.png")));
    }//GEN-LAST:event_lbDellMouseExited

    private void lbGarenaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGarenaMouseEntered
        // TODO add your handling code here:
        lbGarena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_garena_100px_1.png")));
    }//GEN-LAST:event_lbGarenaMouseEntered

    private void lbGarenaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGarenaMouseExited
        // TODO add your handling code here:
        lbGarena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_garena_100px_2.png")));
    }//GEN-LAST:event_lbGarenaMouseExited

    private void lbCorsairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCorsairMouseEntered
        // TODO add your handling code here:
        lbCorsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_corsair_100px_3.png")));
    }//GEN-LAST:event_lbCorsairMouseEntered

    private void lbCorsairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCorsairMouseExited
        // TODO add your handling code here:
        lbCorsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_corsair_100px_2.png")));
    }//GEN-LAST:event_lbCorsairMouseExited

    private void lbLogitechMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogitechMouseEntered
        // TODO add your handling code here:
        lbLogitech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_logitech_100px_1.png")));
    }//GEN-LAST:event_lbLogitechMouseEntered

    private void lbLogitechMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogitechMouseExited
        // TODO add your handling code here:
        lbLogitech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_logitech_100px_2.png")));
    }//GEN-LAST:event_lbLogitechMouseExited

    private void btnSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignMouseEntered
        // TODO add your handling code here:
        btnSign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePng/SignButtonWhite.png")));
        lbLogitech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_logitech_100px_1.png")));
        lbCorsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_corsair_100px_3.png")));
        lbGarena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_garena_100px_1.png")));
        lbDell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_dell_100px_1.png")));
        lbController.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_game_controller_100px_1.png")));
        lbTwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_twitch_100px_1.png")));
        lbRazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_razer_100px_1.png")));
        lbDiscord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_discord_100px_1.png")));
    }//GEN-LAST:event_btnSignMouseEntered

    private void btnSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignMouseExited
        // TODO add your handling code here:
        btnSign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePng/SignButtonGreen.png")));
        lbLogitech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_logitech_100px_2.png")));
        lbCorsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_corsair_100px_2.png")));
        lbGarena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_garena_100px_2.png")));
        lbDell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_dell_100px_2.png")));
        lbController.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_game_controller_100px_2.png")));
        lbTwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_twitch_100px.png")));
        lbRazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_razer_100px.png")));
        lbDiscord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_discord_100px.png")));

    }//GEN-LAST:event_btnSignMouseExited

    private void btnSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignMouseClicked
        // TODO add your handling code here:
        Signin();
    }//GEN-LAST:event_btnSignMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        // TODO add your handling code here:
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_minimize_window_25px_1.png")));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        // TODO add your handling code here:
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_minimize_window_25px.png")));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:
        if (txtUsername.getText().equals("Tài khoản")) {
            txtUsername.setText("");
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void lbQuenMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuenMKMouseEntered
        // TODO add your handling code here:
        lbQuenMK.setForeground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_lbQuenMKMouseEntered

    private void lbQuenMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuenMKMouseExited
        // TODO add your handling code here:
        lbQuenMK.setForeground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_lbQuenMKMouseExited

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
        if (!txtUsername.getText().equals("")) {
            jClearUsername.setVisible(true);
        } else {
            jClearUsername.setVisible(false);
        }
//        jLabelTK.setVisible(false);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Signin();
        }
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        // TODO add your handling code here:
//        jLabelMK.setVisible(false);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Signin();
        }
    }//GEN-LAST:event_jPasswordFieldKeyPressed

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if (txtUsername.getText().equals("")) {
//            jLabelTK.setVisible(true);
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField.getPassword()).equals("")) {
//            jLabelMK.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordFieldFocusLost

    private void txtUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseEntered
        // TODO add your handling code here:
        if (!txtUsername.getText().equals("")) {
            jClearUsername.setVisible(true);
        } else {
            jClearUsername.setVisible(false);
        }
    }//GEN-LAST:event_txtUsernameMouseEntered

    private void txtUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseExited
        // TODO add your handling code here:
        jClearUsername.setVisible(false);
    }//GEN-LAST:event_txtUsernameMouseExited

    private void jClearUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClearUsernameMouseClicked
        // TODO add your handling code here:
        txtUsername.setText("");
    }//GEN-LAST:event_jClearUsernameMouseClicked

    private void jPasswordFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMouseEntered
        // TODO add your handling code here:
        if (!String.valueOf(jPasswordField.getPassword()).equals("")) {
            jClearPassword.setVisible(true);
        } else
            jClearPassword.setVisible(false);
    }//GEN-LAST:event_jPasswordFieldMouseEntered

    private void jPasswordFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMouseExited
        // TODO add your handling code here:
        jClearPassword.setVisible(false);
    }//GEN-LAST:event_jPasswordFieldMouseExited

    private void jClearPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClearPasswordMouseEntered
        // TODO add your handling code here:
        if (!String.valueOf(jPasswordField.getPassword()).equals("")) {
            jClearPassword.setVisible(true);
        } else
            jClearPassword.setVisible(false);
    }//GEN-LAST:event_jClearPasswordMouseEntered

    private void jClearPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClearPasswordMouseExited
        // TODO add your handling code here:
        jClearPassword.setVisible(false);
    }//GEN-LAST:event_jClearPasswordMouseExited

    private void jClearPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClearPasswordMouseClicked
        // TODO add your handling code here:
        jPasswordField.setText("");
    }//GEN-LAST:event_jClearPasswordMouseClicked

    private void pnBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBackgroundMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - XX, y - YY);
    }//GEN-LAST:event_pnBackgroundMouseDragged

    private void pnBackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBackgroundMousePressed
        // TODO add your handling code here:
        XX = evt.getX();
        YY = evt.getY();
    }//GEN-LAST:event_pnBackgroundMousePressed

    private void lbRazerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRazerMouseExited
        // TODO add your handling code here:
        lbRazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_razer_100px.png")));
    }//GEN-LAST:event_lbRazerMouseExited

    private void lbRazerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRazerMouseEntered
        // TODO add your handling code here:
        lbRazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_razer_100px_1.png")));
    }//GEN-LAST:event_lbRazerMouseEntered

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(LoginForm.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void jClearUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClearUsernameMouseEntered
        // TODO add your handling code here:
        if (!txtUsername.getText().equals("")) {
            jClearUsername.setVisible(true);
        } else {
            jClearUsername.setVisible(false);
        }
    }//GEN-LAST:event_jClearUsernameMouseEntered

    private void jClearUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClearUsernameMouseExited
        // TODO add your handling code here:
        jClearUsername.setVisible(false);
    }//GEN-LAST:event_jClearUsernameMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnSign;
    private javax.swing.JLabel jClearPassword;
    private javax.swing.JLabel jClearUsername;
    private javax.swing.JLabel jErrorIcon1;
    private javax.swing.JLabel jErrorIcon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelSign;
    private javax.swing.JLabel jLook;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JSeparator jSeparatorPass;
    private javax.swing.JSeparator jSeparatorUsername;
    private javax.swing.JLabel jUsericon;
    private javax.swing.JLabel lbController;
    private javax.swing.JLabel lbCorsair;
    private javax.swing.JLabel lbDangNhap;
    private javax.swing.JLabel lbDell;
    private javax.swing.JLabel lbDiscord;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbGarena;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLogitech;
    private javax.swing.JLabel lbQuenMK;
    private javax.swing.JLabel lbRazer;
    private javax.swing.JLabel lbTwitch;
    private javax.swing.JLabel lbWrongPass;
    private javax.swing.JLabel lbWrongUsername;
    private javax.swing.JPanel pnBackground;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
